[theme]
base="dark"
primaryColor = "#9b5de5"          # Roxo Pocket principal para botões, checkboxes e abas
backgroundColor = "#0E1117"       # Fundo escuro padrão (Dark Mode)
secondaryBackgroundColor = "#1E232E" # Fundo dos cards e barras laterais
textColor = "#FAFAFA"             # Texto claro
font = "sans serif"
